### ISSUE TITLE
Documentar como fazer campanha de arrecadação

### ISSUE THREAD

**Issue by Dayof** [pyladies-brazil/organizacao#1]
Já foram realizadas 3 campanhas de arrecadação das PyLadies (PyBr12, PyBr13 e FISL). É necessário documentar esta campanha para que a carga seja distribuída e para que possa ser duplicado em outras PyLadies regionais.

**Comment by jtemporal** [comment]
Quero fazer isso! deixa pra mim!

**Comment by pgrangeiro** [comment]
acho mais fácil eu fazer, já que sou eu quem geralmente faz todo o processo.

**Comment by jtemporal** [comment]
@pgrangeiro claro! posso te ajudar nisso! mas tu ta certa

**Comment by deboraazevedo** [comment]
@pgrangeiro alguma novidade sobre a documentação :)
