### ISSUE TITLE
Relatório de gastos para transparência

### ISSUE THREAD

**Issue by pgrangeiro** [pyladies-brazil/organizacao#10]
Criar uma planilha que detalha todos os dados sobre os gastos do PyLadies na PyBR[13]. Incluindo a produção das recompensas e as ajudas de custo. Essa planilha deverá ser disponibilizada para download.

**Comment by talitarossari** [comment]
Onde eu pego esses dados?
Já tem em alguma planilha?
Devo pegar os dados de cada mocinha que participou da campanha?

**Comment by pgrangeiro** [comment]
no nosso drive, já temos uma planilha de gastos onde fui anotando os gastos com hospedagem, ajuda de custo, recompensas, etc. seria pegar esses dados e consolidade numa outra planilha, aberta para quem quiser acessar e consultar

**Comment by talitarossari** [comment]
Ok, vou fazer esta parte. Vou pedir acesso à essa planilha no pvt do Telegram.

**Comment by talitarossari** [comment]
@pgrangeiro, vc pode ver se é essas as informações que devem estar la?
https://docs.google.com/spreadsheets/d/16DHzIkiP5BGNaemX1iU2FlZl9dDi6RDNkoBwfBdeSxM/edit?usp=sharing

**Comment by pgrangeiro** [comment]
@talitarossari perfeito! já está incluído o seu reembolso?

**Comment by talitarossari** [comment]
@pgrangeiro ainda não, pois não sei quanto sera meu reembolso.
Assim que eu tiver o retorno, eu atualizo a planilha!

**Comment by talitarossari** [comment]
@pgrangeiro, atualizei os valores na tabela.
Com o reembolso. Verifique se tem alguma coisa que precise mudar.
Se não, podemos divulgar :)
Caso queira divulgar, quer que eu faça isso?

**Comment by talitarossari** [comment]
ping @pgrangeiro

**Comment by deboraazevedo** [comment]
ping @pgrangeiro  @talitarossari
