### ISSUE TITLE
PyLadiesCon - Indicação de keynote

### ISSUE THREAD

**Issue by cecivieira** [pyladies-brazil/organizacao#103]
Reunir indicações de mulheres para ser keynote na PyLadiesCon.

Prazo: 25 set. 23

**Comment by cecivieira** [comment]
Thais Viana

**Comment by cecivieira** [comment]
Bia Rosa

**Comment by anadulce** [comment]
Ryllari Marques

**Comment by tiidadavena** [comment]
Jess Temporal

**Comment by tiidadavena** [comment]
Alynne Ferreira

**Comment by anadulce** [comment]
Juliana Barros Lima

**Comment by Emilly-horta** [comment]
Karoline Farias (pyladies Teresina)

**Comment by Emilly-horta** [comment]
Ana Paula Mendes (pyladies Teresina)

**Comment by Emilly-horta** [comment]
Valeska Uchoa (pyladies Teresina)

**Comment by Emilly-horta** [comment]
Vitoria Neris (pyladies Parnaiba)

**Comment by Kadidjah** [comment]
Ana Cecília Vieira

**Comment by Kadidjah** [comment]
Ana Dulce

**Comment by BrunaNayara** [comment]
Carla Rocha

**Comment by deboraazevedo** [comment]
Ana Cecília Vieira

**Comment by deboraazevedo** [comment]
Ryllari Marques

**Comment by deboraazevedo** [comment]
Jessica Temporal

**Comment by ingridmurielem** [comment]
Amanda Vieira

**Comment by cecivieira** [comment]
Obrigadaaaa pelas indicações!
As enviei para a organização da PyLadiesCon.
