### ISSUE TITLE
Criar postagem de review da PyBR[13]

### ISSUE THREAD

**Issue by pgrangeiro** [pyladies-brazil/organizacao#12]
É necessário criar uma postagem de review da PyBR[13] em nosso site.

**Comment by talitarossari** [comment]
Essa postagem seria de review da PyBR para as Pyladies, citando as nossas palestras. Ou seria uma postagem de como foi a PyBR na visao de uma Pylady?

**Comment by pgrangeiro** [comment]
acho os dois formatos interessantes... quem sabe duas postagens então? haha

**Comment by talitarossari** [comment]
Posso fazer uma postagem sobre como foi a PyBR na minha visão, contando sobre a casa, experiencia de palestrar e tals.
Devo fazer no Medium ou no próprio site das Pyladies?

**Comment by letuche** [comment]
Faz no site, Talita! Nada impede de publicar nos dois lugares, mas acho importante ter no nosso blog também :)

**Comment by letuche** [comment]
A Victória de Salvador escreveu um legal, olhem: https://medium.com/pyladies-salvador/sobre-minha-primeira-python-brasil-parte-1-206ef59fe5f4

**Comment by talitarossari** [comment]
Gostei bastante do texto dela \o/
Ja foi compartilhado na page da Pyladies BR? 

Quanto ao meu texto. To esperando saírem as fotos oficias :P
