### ISSUE TITLE
Solicitar criação do grupo PyLadies Sorocaba

### ISSUE THREAD

**Issue by pgrangeiro** [pyladies-brazil/organizacao#14]
Os dados para criação estão na nossa caixa de email oficial.

**Comment by giovana-morais** [comment]
oi gente!

essa issue teve alguma conclusão? ontem fizemos uma reunião pra reviver o PyLadies Sorocaba e gostaria de saber se existe algo que eu possa fazer pra ajudar? alguma informação atualizada ou etc?
