### ISSUE TITLE
Atualizar a página de Eventos no site da PyLadies Brasil

### ISSUE THREAD

**Issue by anapaulamendes** [pyladies-brazil/organizacao#15]
Na seção "Eventos Anteriores" há muitos eventos que não foram registrados;
Na seção "Próximos Eventos" não há eventos registrados.

Sugestão: Se não houver um plug-in que atualize o site com  os eventos que estão registrados no Facebook, poderia ser listado todos os eventos que aconteceram e acontecerão e ser adicionados no site. Caso seja necessário listar todos os eventos, poderia ser uma nova Issue ou esta tarefa estaria incluida nesta?!

**Comment by talitarossari** [comment]
@darlenedms, tem algo assim no site? Um plugin para o fb?
Consegue ajudar a @anapauladsmendes nisso?

**Comment by darlenedms** [comment]
Existe o plugin padrão do Facebook, que é bem fácil de colocar, porém não podemos mexer muito na interface dele, ficando mais ou menos assim:

<img width="341" alt="screen shot 2017-10-17 at 3 29 13 pm" src="https://user-images.githubusercontent.com/850280/31679558-3fba6b30-b350-11e7-967c-e9aad039e0f1.png">

ou

<img width="342" alt="screen shot 2017-10-17 at 3 30 52 pm" src="https://user-images.githubusercontent.com/850280/31679565-43741cbc-b350-11e7-8f74-86b717db3b71.png">

E existe uma opção um pouco mais trabalhosa que seria integrarmos com a API do Facebook para exibir os dados do jeito que quisermos (respeitando a interface da nossa página de eventos hoje).

**Comment by talitarossari** [comment]
Mas dai os eventos sempre tem que ser criados pelas pyladies brasil né?

**Comment by darlenedms** [comment]
Não, tanto no caso de plugin quanto da API podemos acessar várias páginas.
O problema no caso do plugin é que teremos vários "quadrados" (um pra cada página) sendo exibidos mesmo que não tenham evento - a menos que façamos uma gambiarra pra esconder do nosso lado mas ae se é pra ter trabalho, melhor acessar a API e fazer "direito".

**Comment by rsip22** [comment]
Atualizei com eventos aqui do RS. PR #194
