### ISSUE TITLE
Levantar os valores/orçamento para a Pyladies Conf

### ISSUE THREAD

**Issue by talitarossari** [pyladies-brazil/organizacao#17]
Como foi decidido durante a reunião (#13), agora a @deboraazevedo vai fazer o levantamento dos valores que vão ser gastos na Pyladies Conf.
Para aí sim continuarmos a discutir os outros itens que foram levantados na pauta (https://docs.google.com/document/d/1QX9FCoxxezLa8D4Hmwk09zyVtqzBMLH9VArIRMExK3I/edit?usp=sharing)

**Comment by kessiacastro** [comment]
A planilha com o orçamento inicial já foi organizada. Queremos comentários/dicas/sugestões e se alguém tiver algum orçamento de algum outro lugar do Brasil é super válido também. Segue o link para visualização: https://docs.google.com/spreadsheets/d/1D9A9hQxkg5dFr2H9zAvli_HJW3iTGi_sLZMZnkCS7nE/edit?usp=sharing
