### ISSUE TITLE
Criar post sobre canais de comunicação

### ISSUE THREAD

**Issue by Dayof** [pyladies-brazil/organizacao#2]
No site PyLadies criar um post informando sobre os canais de comunicação, anunciando sobre o procedimento de como informar possíveis tarefas e como é possível colaborar na organização (através de issues).

**Comment by talitarossari** [comment]
Isso seria no Blog?
Pois, se for no Blog, pode ser que se perca com o tempo, teria que ser fixado no começo...

**Comment by biancarosa** [comment]
@talitarossari acho que é uma comunicação pontual e quem for entrando já vai saber, mas acho melhor comunicar pontualmente via lista de e-mail

**Comment by anapauladsmendes** [comment]
Como seria o formato disso? Explana mais, please!

**Comment by talitarossari** [comment]
Então seria um post explicando como esta sendo o procedimento de comunicação de necessidades?
Explicando esse project no github?

**Comment by deboraazevedo** [comment]
Acho que um post no site do PyLadies em uma seção de "Contato" seria uma boa
