### ISSUE TITLE
[Reunião] Grupo de Trabalho Comunicação: 18 set. 2020

### ISSUE THREAD

**Issue by cecivieira** [pyladies-brazil/organizacao#22]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêncide no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião Grupo de Trabalho Comunicação

- Data: 18 ago. 2020  
- Participantes:

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) | 
 --| --| --|
PyLadies Sergipe| Bárbara Mota| @barbaramsantana| 
PyLadies Sergipe| Thais Campos| @Thcamposmartins| 
PyLadies Recife| Ana Cecília Vieira| @cecivieira |
PyLadies São Carlos| Ana Dulce| @anadulce |
PyLadies Rio de Janeiro| Gabriela Entringe| @gabientringe |
PyLadies Parnaíba| Emilly Horta| @Emilly-horta |

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Acompanhamento das ações pendentes da última reunião

Atividade| Responsável | Link útil| Observações|
-- | -- | --| --
Escrever templates para resposta a contatos recebidos sobre divulgação de vaga de emprego, cursos e programas | @deboraazevedo @anadulce | --| Não realizado
Escrever template para resposta a empresa que no primeiro contato  pede reunião, nossa resposta será pedindo resumo do assunto para o  assunto serque seja levado para a comunidade | @deboraazevedo @anadulce | --| Não realizado
Atualizar CONTRIBUTING.md (site).  Na sessão de Post adicionar: Link para código de conduta, Link para  forms para enviar post, como alternativa para quem não quer mexer no  código e enviar PR | @cecivieira | --| Não realizado

### Itens a serem debatidos

- [x] Canal de notícias no Telegram - Novas publicadoras
Objetiva divulgação das atividades das comunidades PyLadies do país e o que as mulheres estão produzindo e/ou protagonizando. Esse canal é público, então todo mundo poderá segui-lo para saber o que estamos fazendo (aproveita segue lá e compartilha ele no grupo da tua comunidade).

O que NÃO é objeto de divulgação no canal de notícias:
- Vagas de emprego;
- Programas de bolsas;
- Cursos promovidos por empresas, etc.

- [x] Recebimento de patrocínio fixo de empresas
De acordo com o definido na reunião anterior, enquanto rede de comunidades não temos voluntárias para realizar estudo sobre o ambiente de trabalho das empresas e garantir espaço seguro para as mulheres que seguirão nossa indicação.

@gabientringe sugeriu desenvolver uma política de patrocínio para a rede de comunidades.

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|

cc @pyladies-brazil/comunicacao

**Comment by anadulce** [comment]
Acho ótimo fixarmos uma data. por mim, tirando segunda-feira que é reunião da PyBR e terça que é grupo de estudos, todas as outras são ótimas!
@cecivieira coloca um deadline pra essas coisas que eu tô marcada, por favor! Eu pretendo fazer esse fim de semana, mas tô devendo vááárias coisas, então fico preocupada em acabar esquecendo essas também.

**Comment by cecivieira** [comment]
@anadulce aonde essa data limite deve aparecer? Ela pode ser 1 dia antes da próxima reunião

**Comment by anadulce** [comment]
A gente deveria ter um trello pra essas coisas.

**Comment by cecivieira** [comment]
@anadulce  Podemos criar um kanbam aqui nesse repositório, tal qual um trello. O que tu acha?
Também estava pensando nisso para substituir o calendário que estávamos testando e não serviu

**Comment by anadulce** [comment]
Não sabia que isso existia! Super apoio!

**Comment by pamellabiotec** [comment]
Essa reunião está agenda ainda para essa data ou será remarcada para outra data? Se sim, qual será?

**Comment by cecivieira** [comment]
@pamellabiotec 
Boa parte dessa reunião seria apresentar a programação de publicações nas redes sociais e começar a montar um programa. @CarolineGaliza começou a conversa no Slack, mas não andamos muito. Eu não conseguirei dar andamento a isso durante essa semana. 

Por mim, deixa para a semana que vem, mas se @CarolineGaliza tiver algo para apresentar, acho que vale puxar a reunião para quinta ou sábado para que não choque com o encontro do grupo de estudo (criação de material)
