### ISSUE TITLE
[Reunião] GT de Materiais: 11 set. 2020

### ISSUE THREAD

**Issue by cecivieira** [pyladies-brazil/organizacao#27]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêndice no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião GT de Materiais

- Data: 11 set. 2020  - 19h
- Participantes:

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) |
 --| --| --|
PyLadies Recife | Ana Cecília Vieira | @cecivieira
PyLadies Recife | Amanda Savluchinske | @amandasavluchinske
PyLadies Recife | Chaina Oliveira | @chainao
PyLadies Recife | Carolina Brito | @coab1
PyLadies São Carlos | Ana Dulce Padovan | @anadulce
PyLadies São Carlos | Amanda Manso | @amandpmn
PyLadies São Carlos | Thayana Tavares | @thayanavt
PyLadies Macaé | Renata Pereira Martins Gomes| @22renata
PyLadies São Paulo | Jessica Guimaraes Freitas | jessica.graes@gmail.com
Taubaté (SP) | Maria Paula Dias Rosa | @mpdiasrosa
PyLadies Blumenau | Amanda de Oliveira Casagrande | @amandacasagrande
PyLadies Natal | Mariana | @mrncstt 
PyLadies Mato Grosso | Pâmella Araújo Balcaçar | @pamellabiotec 
Brasília (DF) | Kadidja Valéria Reginaldo de Oliveira | kadidja.oliveira@gmail.com
PyLadies Natal | Débora Azevedo | @deboraazevedo
PyLadies Recife | Caroline Brito | @COAB1

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Acompanhamento das ações pendentes da última reunião

Atividade| Responsável | Link útil | Observações|
 --| --| --| --|
Revisão de materiais e trazer uma proposta de conteúdo programático para o Grupo de Estudo Introdução a Python | Todas | [Link 1](https://drive.google.com/folderview?id=1jN8sXfEpQ7JiFrJllpwlVgGekNOLBDU6), [Link 2](https://github.com/PyLadiesSP/Cursos/blob/master/B%C3%A1sico%20I/B%C3%A1sico%201.pdf), [Link 3](https://docs.google.com/document/d/1Dx8pGkJCzrAeam8Q3K5uam5ze9jLrGk7Sku0zwD3K-g/edit), [Link 4](https://github.com/PyLadiesNatal/minicurso-intro-python), [Link 5](https://docs.google.com/presentation/d/1hXtL5mr1pPQ0tYX0cFcHP1G2ZYGBfNX3JvcNTVddRTo/edit?usp=sharing), [Link 6](https://docs.google.com/presentation/d/1CLawydiOsuAwORx3Pu07hpWIYL-1trhTBuotu8HxAIM/edit?usp=sharing)|
 Após análise do material, montar uma proposta de conteúdo programático para próxima reunião | Todas | --|--|
 Material para GE Python intermediário | @thayanavt | --|--|

### Itens a serem debatidos

- [x] Construção do conteúdo programático para Grupo de Estudo de Introdução a Python

- [x] Atribuição de responsabilidade por conteúdo

@mrncstt Adotar a prática de ter um exercício no final das aulas para que durante a semana as mulheres possam praticar

@amandacasagrande Ementa exemplo: https://drive.google.com/file/d/1I3e3jILpMy0NeL8JavgAbZh-kxTdkIfA/view?usp=sharing

Curso:  Introdução a python para quem já sabe programar (1h30min por aula)

**Aula 1 - Ana Cecília, Débora Azevedo, Maria Paula, Renata Pereira** ([Slides](https://docs.google.com/presentation/d/1uAddfXsGA0qk5Z0f93l-Bdo-j3imWrwSBlmprrWE7Bw/edit?usp=sharing))
Motivação à linguagem (história, aplicações, diferenciais, Zen do Python)
Introdução à lógica de programação (indentação, revisão - nome variável, tipagem. Fazer a revisão usando usar o terminal python interativa)
Operadores aritméticos
Exercício para casa
Lista de operações para resolver no Python

**Aula 2 - Amanda Manso, Chaina Oliveira, Maria Paula, Renata Pereira** ([Slides](https://docs.google.com/presentation/d/1gZmof4Zg_EfI7m7G3Y0BOiFphaoyQLkgRYAmsIHTZmo/edit?usp=sharing))
Revisar conteúdo da aula anterior através da resolução do exercício
Operadores lógicos (==, !=) + tabela verdade (and, or)
Estruturas lógicas e condicionais (If, else, elif/and, or, not, is)
Estruturas de repetição (For loop, while loop, break, continue, exit)
Exercício para casa

**Aula 3 - Ana Dulce, Pâmella, Renata Pereira** ([Slides](https://docs.google.com/presentation/d/1Yy2rPiXk4sfCMC7w62tl32Rkx4r8zDJECY7Kmqvr2_U/edit?usp=sharing))
Revisar conteúdo da aula anterior através da resolução do exercício
Estruturas de dados (listas, dicionários, tuplas…)
Revisão de Estruturas de repetição (For loop, while loop, break, continue, exit)
Exercício para casa

**Aula 4 - Amanda Manso, Renata Pereira, Thayana (Belém)** ([Slides](https://docs.google.com/presentation/d/1RD871_3l9dLdPWJHacmskGQJR3EonoKc-y0f0niK2TI/edit?usp=sharing))
Revisar conteúdo da aula anterior através da resolução do exercício
Funções
Classes
Exercício para casa
    
**Aula 5 - Amanda Manso, Ana Cecília, Ana Dulce, Caroline Brito, Débora Azevedo, Maria Paula, Renata Pereira, Pâmella** ([Slides](https://docs.google.com/presentation/d/1AAroM27InjChu8vJSpIdj6kimErFaONpIh_TFTby9dY/edit?usp=sharing))
Revisar conteúdo da aula anterior através da resolução do exercício
Bibliotecas (como usar, bibliotecas nativas)
Git + Github 
Construir projetinho revisando todo o conteúdo e enviar para repositórios próprio
 
Padrões:
Todos os exemplos e exercícios precisam estar associados com as comunidades PyLadies;
Todo o texto flexionado no gênero feminino;
Usar imagens que representem diversidade;
Usar imagens com licença aberta;
Não usar fotografia e gifs, apenas desenhos

Links de banco de imagens com licença abertos:
https://unsplash.com/
https://br.freepik.com/fotos-vetores-gratis/banco-de-imagens 
https://pixabay.com/pt/
https://www.pexels.com/
https://www.shopify.com.br/burst
https://gratispng.com/

- [x] Escolha da ferramenta para organização do trabalho

Será criado repositório no Github da PyLadies Brasil para o grupo de estudo e as atividades serão organizadas no Projeto.

@amandasavluchinske Queria ficar responsável por organizar essas tarefas de produção de conteúdo e criar um quadro no Asana (de preferência, porque acho a ferramenta a mais completa). Acho que facilitaria o acompanhamento das tarefas porque daria pra gente colocar datas de entrega, requisitos, materiais, entre outras coisas. Se não puder ser no Asana, é ok também. Sugeri porque trabalho com Asana e já usei kanban no Git e no Trello e acho o Asana melhor. Desde que seja Kanban tá ótimo kkkk Não tenho email da PyLadies, acho que seria legal criar em algum email das PyLadies.

- [x] Criação de repositório para guarda do conteúdo produzido (exercícios, testes)

Foi criado o [repositório Curso de Introdução a Python](https://github.com/pyladies-brazil/curso-introducao-python) no Github da PyLadies Brasil para guarda e compartilhamento do material produzido para o grupo de estudo.

- Amanda: Também acho que seria legal criar um repositório para o curso na organização do GitHub das PyLadies para organização do material, links para as aulas, exercícios, etc. 

- [x] Grupo de estudo Intermediário

Juliana Ferreira: A aula de POO finaliza na na terça que vem se não houver problemas e em seguida continuamos com o manipulação de arquivos.
Ainda não encontramos alguém para falar de decorators
Sobre arquivo binário ele não parece ser tanto escopo de intermediário, apesar de ser muito importante. Seria interessante passar apenas se alguém tiver interesse de explicar "representação binária: como e pq"

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|
Desenvolver opções de layout para slide mestre | Todas| [Layout Canva](https://www.canva.com/design/DAEHULiIwE0/share/preview?token=8hKgkHGFQFwolRAWTrgXNQ&role=EDITOR&utm_content=DAEHULiIwE0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton#1) |
Desenvolver o material das aulas| --| [Aula 1 - Slide ](https://docs.google.com/presentation/d/1uAddfXsGA0qk5Z0f93l-Bdo-j3imWrwSBlmprrWE7Bw/edit?usp=sharing), [Aula 2 - Slide ](https://docs.google.com/presentation/d/1gZmof4Zg_EfI7m7G3Y0BOiFphaoyQLkgRYAmsIHTZmo/edit?usp=sharing), [Aula 3 - Slide ](https://docs.google.com/presentation/d/1Yy2rPiXk4sfCMC7w62tl32Rkx4r8zDJECY7Kmqvr2_U/edit?usp=sharing), [Aula 4 - Slide ](https://docs.google.com/presentation/d/1RD871_3l9dLdPWJHacmskGQJR3EonoKc-y0f0niK2TI/edit?usp=sharing), [Aula 5 - Slide ](https://docs.google.com/presentation/d/1AAroM27InjChu8vJSpIdj6kimErFaONpIh_TFTby9dY/edit?usp=sharing) |
Estabelecer um horário da semana e quem vai ministrar a aula| Responsáveis pela produção de material| --|

cc @<GitHub team do grupo de trabalho responsável pela reunião>

**Comment by anadulce** [comment]
@cecivieira mais um material: https://docs.google.com/presentation/d/1CLawydiOsuAwORx3Pu07hpWIYL-1trhTBuotu8HxAIM/edit?usp=sharing
Tô mexendo alguma coisa nele, mas tá bem ok.

**Comment by anadulce** [comment]
@cecivieira o último docs que eu mandei não está nos links não :)

**Comment by cecivieira** [comment]
@anadulce Tu poderia enviar de novo? Não tô conseguindo recuperar a mensagem

**Comment by anadulce** [comment]
https://docs.google.com/presentation/d/1CLawydiOsuAwORx3Pu07hpWIYL-1trhTBuotu8HxAIM/edit?usp=sharing

**Comment by amandasavluchinske** [comment]
Capítulo | Nome e sobrenome | @github ou e-mail (opcional)
-- | -- | --
Recife | Amanda Savluchinske | @amandasavluchinske

**Comment by anadulce** [comment]
PyLadies São Carlos

**Comment by chainao** [comment]
PyLadies Recife

**Comment by amandapmn** [comment]
PyLadies São Carlos
