### ISSUE TITLE
Documentar o processo de criação de um PyLadies regional

### ISSUE THREAD

**Issue by Dayof** [pyladies-brazil/organizacao#3]
Informar sobre os procedimentos da criação de um novo grupo.

**Comment by talitarossari** [comment]
O que precisamos fazer para criar essa base? Que info temos que dar?
Pois temos um handbook já: http://pyladies-brasil-handbook.readthedocs.io/en/latest/
Vocês querem fazer algo mais parecido com o Django Girls?

**Comment by pgrangeiro** [comment]
@talitarossari acho legal continuar usando o handbook, mas atualizá-lo. Ele por exemplo orienta a pessoa a entrar em contato conosco por email, quando na verdade é necessário entrar em contato com o pyladies internacional. A ideia de entrar em contato conosco seria para sabermos sobre os pyladies nacionais criados, porém cria uma burocracia porque gera a responsabilidade de quem acessa o email do pyladies brasil (geralmente eu) fazer o processo para criar o pyladies -  que poderia ser feito pelos próprios interessados.

**Comment by anapauladsmendes** [comment]
Quando eu procurei para começar em Teresina vi que muitos materiais disponíveis estavam desatualizados, inclusive tinha contatos errados. Teria como fazer modificação do handbook? Ou criar uma nova documentação mais simples?

**Comment by talitarossari** [comment]
@pgrangeiro, acredito que a questão de ter centralizado no Pyladies Brasil esse envio do email seja pelo ingles e pelo conhecimento que vocês ja tem pelo processo. Podemos criar um email "base", que seria só trocar os nomes e regiao das pessoas envolvidas

**Comment by talitarossari** [comment]
@anapauladsmendes, tive o mesmo problema que você quando fui puxar o de Floripa. Mas como ja conhecia as meninas, incomodamos elas :P
O que você encontrou de informação incorreta?

**Comment by talitarossari** [comment]
@anapauladsmendes, olhei aqui, e a documentação esta na plataforma do readthedocs.
Neste projeto aqui: https://readthedocs.org/projects/pyladies-brasil-handbook/
Então todas podemos melhorar ela.
Só não sei onde esta no github o projeto

**Comment by letuche** [comment]
Só uma ideia: e se pedíssemos para entrar em contato com o PyLadies
internacional, mas com o PyLadies BR em cópia? Assim eles se resolvem por
lá e nós continuamos tendo registro da criação de novas unidades regionais,
mesmo que não o consultemos em tempo real.

Em 11 de outubro de 2017 11:53, Talita Rossari <notifications@github.com>
escreveu:

**Comment by anapauladsmendes** [comment]
@Dayof conclui a documentação. Segue o link para o repositório: https://github.com/pyladies-brazil/documentation-creation-regional-pyladies/blob/master/documentation.md 

Está tudo ok?

**Comment by rsip22** [comment]
Talvez aqui não seja o melhor lugar, mas é onde o arquivo está citado pela @talitarossari e não se sabe o Github ainda, então:

Podemos deixar explícito em algum lugar que, para PyLadies promoverem um evento que não é PyLadies, o mínimo que esse evento deve ter é um código de conduta explícito?

**Comment by letuche** [comment]
Isso talvez possa ser temporariamente resolvido com um blog post explicando
o que é código de conduta e sua importância. Posso me oferecer para
escrever, mas no momento estou muito enrolada (devendo o post final de
agradecimentos até agora, espero conseguir upar hoje ainda)

**Comment by deboraazevedo** [comment]
Concordo, acredito que o post no blog explicando seria show.. até bom porque "centraliza" algumas informações tipo FAQ no site do PyLadies Brasil
