### ISSUE TITLE
[Reunião] Reunião do Grupo de Bioinformática: 10 out. 2020

### ISSUE THREAD

**Issue by pamellabiotec** [pyladies-brazil/organizacao#34]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêndice no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião do Grupo de Bioinformática

- Data: 10 out. 2020  
- Participantes:

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) | 
 --| --| --|
PyLadies Mato Grosso | Pâmella Araújo Balcaçar | @pamellabiotec |
Pyladies São Carlos     | Thayana Tavares | @thayanavt |
 Pyladies                      | Thayná Felizardo| @thayfelizardo |
PyLadies São Carlos    | Juliana F. Alves   | @julianafalves |
PyLadies São Carlos    | Silvana Cardoso | @psherman43 |
 Pyladies                      | Mariana Gomes | @marianapgs |
PyLadies                      | Clara Cerqueira | @ccmt |

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Acompanhamento das ações pendentes da última reunião

Atividade| Responsável | Link útil| Observações|
 --| --| --| --|

### Itens a serem debatidos

- [x] Integração e organização do grupo, mais descrição no [repositório](https://github.com/pyladies-brazil/grupo-estudo-bioinformatica/blob/main/README.md);
- [x] Bonecas - identidade visual do grupo de estudo;
Foram apresentados 3 modelos de bonecas que ficarão disponíveis no slack para análise e votação.
- [x] Início da [fase 1](https://github.com/pyladies-brazil/grupo-estudo-bioinformatica/issues/2) - seleção do exercício;
Foram mostrados alguns scripts dos exercícios **A** da *fase 1* ficando definido que serão, posteriormente, adicionados no repositório do github do [grupo de bioinformática](https://github.com/pyladies-brazil/grupo-estudo-bioinformatica) organizado dentro da **pasta fase 1**, com nome do arquivo sendo **Exercício_A1_NomePylady** e **Exercício_A2_NomePylady**.
- [x] Discutir se a próxima fase pode ser feita em outro dia, pois temos membras que guardam os sábados

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|
Realizar um doodle para definir uma nova data para os encontros quinzenais  | @thayanavt |  |
Colocar as bonecas no slack para serem analisadas e votadas | @pamellabiotec | |
Subir os arquivos dos exercícios para o github | todas | https://github.com/pyladies-brazil/grupo-estudo-bioinformatica |

cc @<GitHub team do grupo de trabalho responsável pela reunião>

**Comment by thayanavt** [comment]
Discutir se a próxima fase pode ser feita em outro dia, pois temos membras que guardam os sábados
