### ISSUE TITLE
[Reunião] Reunião GT Criação de Material: 22 out. 2020 

### ISSUE THREAD

**Issue by 22renata** [pyladies-brazil/organizacao#37]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêncide no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião <Grupo de trabalho ou tema da reunião>

- Data: 22/10/2020
- Participantes:

Capítulo | Nome e sobrenome | @github ou e-mail (opcional)
-- | -- | --
PyLadies Recife  | Ana Cecília Vieira | @cecivieira
PyLadies Macaé | Renata | @22renata
PyLadies Recife  | Fernanda | @naanadr
PyLadies Brasília  | Kadidjah| @kadidjah
PyLadies Natal  | Débora | @deboraazevedo 
PyLadies ?  | Pâmela| 
PyLadies ?  | Amanda

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) | 
 --| --| --|

## Ata

Discutimos sobre desenvolver um projeto ao longo do curso, porém, o produto ainda não foi definido. 
Pensamos em criar uma Sprint para o Projeto, com entregas por grupo ou individual?
Essas entregas poderiam ser exercícios resolvidos que refletem a identificação com o uso da linguagem Python. O objetivo é aprender a linguagem Python.

### Acompanhamento das ações pendentes da última reunião

Atividade| Responsável | Link útil| Observações|
 --| --| --| --|

### Itens a serem debatidos

- [ ] Metodologia de projetos
- [ ] Uso de metodologias ativas
- [ ]
- [ ]
- [ ]

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|

Pensar na construção de sprint para o projeto com entregas de atividades de aprendizagem por grupo ou individual.
Sugerir atividades de aprendizado: turtle, crud etc.

cc @<GitHub team do grupo de trabalho responsável pela reunião>

**Comment by cecivieira** [comment]
@22renata @naanadr o que ficou decidido para a próxima reunião?
Coloca um resuminho na ata
