### ISSUE TITLE
[Reunião] Assembleia nacional rede PyLadies Brasil: 07 nov. 2020

### ISSUE THREAD

**Issue by cecivieira** [pyladies-brazil/organizacao#40]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêndice no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Assembleia nacional rede PyLadies Brasil - 2020

- Data: 07 nov. 2020
- Participantes:

Capítulo | Nome e sobrenome | @GitHub ou e-mail (opcional) |
:--:|:--:|:--:|
Rio de Janeiro | Bianca Rosa | @biancarosa |
São Paulo | Daviny Vidal | @davinyvidal
Natal | Mariana Costa | @mrncstt
DF | Bruna Moreira | @brunanayara
Paraíba | Dandara Sousa | @dandaramcsousa 
Brasil | Jessica Temporal | @jtemporal
Recife | Lidiane Monteiro | @lidymonteiro
Brasil | Pâmella Araújo Balcaçar | @pamellabiotec
São Paulo | Alynne Ferreira | @alynnefs
DF / Vancouver | Tânia Andrea | @taniaa
Paraíba | Vanessa Sidrim | @vanessasidrim
Ribeirão Preto/Sul de Minas | Isabela Figueiredo | @belafig
Recife | Ana Cecília Vieira | @cecivieirareto 
Sergipe | Liggia Lima | @liggialima
Macaé-RJ | Renata Pereira | @22renata
Blumenau | Alini Ribeiro | @liniribeiro
Sergipe | Lis R. Barreto | @lis-r-barreto
São Carlos | Ana Dulce | @anadulce
Manaus / Ireland | Loyanne Repolho | @loyannec
São Paulo | Patrícia do Nascimento | @pathilink 
Natal | Esther Aragão | @estheraragaos 
Natal | Débora Azevedo | @deboraazevedo
Parnaíba | Emilly Horta | @Emilly-horta
São Carlos | Juliana F. Alves |@julianafalves
Recife | Allana Evellyn Mendes | @allanina 
Natal | Gabi Cavalcante | @gabicavalcante

## Ata    

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Acompanhamento das ações pendentes da última reunião

Atividade| Responsável | Link útil| Observações|
 --| --| --| --|

### Itens a serem debatidos

- [x] Boas vindas às novas ladies

**RETROSPECTIVA**

- [X] Campanha PyLadies na Python Brasil 2020 (https://www.catarse.me/pyladies_na_python_brasil_2020)
    - Quase todos os estados têm uma representante na organização da campanha
    - Migração do canal do GT da campanha no slack (provavelmente, janeiro)
    - Cap @jtemporal
    - SP @anadulce
    - RN @deboraazevedo
    - CE @ryllari
    - PE @anicely_santos
    - BA @MilenaFerreira
    - PI @anamariatop
    - AM @giovanadelucca
    - GO @karenpess
    - RJ @leticiavna
    Link para ser representante da campanha: https://brasil.pyladies.com/2020/02/13/chamada-representantes-campanha-pybr2020/ 

    Papel das representantes: ajudar a divulgar a Campanha de arrecadação dentro das comunidades do seu estado.
    As pessoas que vão definir não são as mesmas que pedirão o auxílio
    

- [X] Modelo de Governança (mini assembleias locais, levantamento de dados das comunidades, grupos de trabalho, criação de wiki para centralização e democratização de manuais de eventos, dicas e guias, atualização de informação do site)
    - Levantamento das comunidades está no site (existentes e ativos): http://brasil.pyladies.com/locations/ 
Critério: 
- redes sociais que não tinham postagem no último ano

Mini assembleias locais:
o problema era melhorar a comunicação e resgatar os números de cada capítulo (quantos eventos, participantes, etc)
A comunicação melhorou com o uso do slack e email.
Wiki:
grupo de trabalho de documentação existe e está trabalhando 

- [x] Racismo (comissão de minorias para desenvolver ações para que não volte a ter casos de racismo, como ocorrido)

    - Divulgar o manifesto (feito em certo momento político do Brasil): https://github.com/pyladies-brazil/manifesto 
    - Divulgar o Código de conduta (permanente e que cobre todos nossos canais): https://github.com/pyladies-brazil/coc 
    - Criação do grupo de trabalho no slack:
    - Como ser mais inclusiva com todos os grupos e não só mulheres brancas
        - Fazer Email de convocação para este grupo 
                       - fazer censo de mulheres trans presentes na comunidade (sugestão de Naomi Ceder)
        - Todas as minorias
    - Responsável pelo envio do e-mail : Renata (Pyladies Macaé-RJ)

**PLANEJAMENTO 2021**
- [x] Comunicação (um olhar crítico no que evoluímos sobre horizontalidade e transparência, e onde estamos deixando a desejar)
    - Horizontalidade e transparência nas comunicações
                       - divulgar o uso essencial do slack como plataforma oficial de participação horizontal (reforçar que todas devem estar à vontade para participar!) e ações
               - Em qual momento levamos as discussões do Telegram ou outro canal para o slack (oficial)? O mais cedo quanto percebermos que um assunto pode virar alguma movimentação. Isso permitirá que mais pessoas participem e encontrem o assunto para contribuir.
        - verificar criação de grupos no slack para os grupos de trabalho
        - verificar criação do PyLadiesBrasilBot dando bom dia toda segunda-feira :)
        - descrição dos canais dos grupos de trabalho nas docs do PyLadies + post no site (https://hackmd.io/qFqUY_MNTsOJNYwU3TOb2Q/badg)

- [x] Evento de inclusão e empoderamento das mulheres trans
              - Ideia é articular um evento para inclusão e empoderamento das mulheres trans, @davinyvidal irá puxar uma thread para divulgar essa discussão.
- [x] Criação do Grupo de Trabalho de Analytics
    - Ideias: relatório anual, entender como nosso grupo está a partir de coleta de dados e métrica estabelecidas (por ex.: taxa de crescimento de cada rede)
    - Email para convocação para este grupo
    - Será considerado a LGPD;
- [x] Projeto PyBabies
    - O projeto PyBabies é nosso! Lançado oficialmente na PyBr de Floripa.
            - Divulgação do projeto
        - @pybabies nas redes: twitter, telegram e github.
                       - mais info no site Calango Hacker Club https://calango.club/temas/pybabies e vídeo YouTube https://youtu.be/fGfnywA2Oe8

    - Na organização dos eventos PyLadies ou Django Girls, pensar no acolhimento dos PyBabies e também das mães dos PyBabies para que ambos tenham uma experiência incrível no evento (não é só ocupar a criança enquanto o parente participa de um evento ou workshop!)
    - Sugestão: conhecer o grupo Aprenda a Programar Jogando (UFRJ - Macaé-RJ), eles desenvolvem vários cursos e oficinas para crianças (6 a 14 anos) e usam python.
           - lembrança: Sempre ver questão legal de ter crianças no evento. ;)

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|
Convocação para o GT de Analytics | @dandaramcsousa | <e-mail a ser enviado até o fim de novembro>
Convocação para o GT de comissão de minorias | @22renata | <e-mail a ser enviado até fim de novembro>
Migração do canal de comunicação do GT da campanha para o slack | @jtemporal | feito até janeiro
Falar com GT Tech para ver a viabilidade de trocar o nome do repositório coc para algo mais explícito | @cecivieira | https://github.com/pyladies-brazil/coc

cc @<GitHub team do grupo de trabalho responsável pela reunião>

**Comment by cecivieira** [comment]
https://drive.google.com/file/d/1iHeJH6pr5AZJKv_aSt_-CtgtfKc1HrEw/view?usp=sharing

Ata da Assembleia nacional 2019.

Ler, descatar pontos que seriam desenvolvidos durante esse ano e colocar na pauta

**Comment by pamellabiotec** [comment]
Não seria muitas pautas para pouco tempo de assembleia?

**Comment by pamellabiotec** [comment]
Inserir essa pauta para planejamento da 2021: Proposta de evento que aborde mulheres trans; (desenvolver mais com @davinyvidal)

**Comment by cecivieira** [comment]
@pamellabiotec acrescentei na pauta o que tu sugeriu e os pontos da última assembleia para ver o que foi feito (dores e glórias)

**Comment by cecivieira** [comment]
Ata para construção colaborativa durante a assembleia:
https://docs.google.com/document/d/17eW9ghsvL43MsW5W-pwL9RCbfXUcG3Nze_XS4QDXYY0/edit?usp=sharing

Após a atividade, passar informações para a issue e fechá-la.

**Comment by pamellabiotec** [comment]
Olá
Poderia inserir mais um subitem da pauta planejamento 2021? 
- PyBabies
