### ISSUE TITLE
Problema para solicitar grupos PyLadies 

### ISSUE THREAD

**Issue by pgrangeiro** [pyladies-brazil/organizacao#6]
Para criar um novo grupo PyLadies, é necessário submeter o pedido em um form disponível no site do [PyLadies Internacional](http://pyladies.com). Porém, desde outubro/2016 os pedidos submetidos não obtiveram resposta. É necessário entrar em contato com o PyLadies Internacional para verificar o que tem acontecido. A pessoa que for pegar essa issue deve ser fluente em inglês para escrever este email.

**Comment by talitarossari** [comment]
@darlenedms, @deboraazevedo, @Dayof vocês conseguem dar uma mão nisso?

**Comment by deboraazevedo** [comment]
Posso fazer isso, queria ter acesso ao e-mail para agilizar.

**Comment by jtemporal** [comment]
Posso passar o acesso pra tu @deboraazevedo ! me manda um ping no telegram que providencio e te ajudo!

**Comment by letuche** [comment]
Oi, gente, o email já foi enviado? Posso mover o card dessa issue para "doing"?

**Comment by deboraazevedo** [comment]
Pode sim, enviei!

**Comment by jtemporal** [comment]
@deboraazevedo sabe se tivemos resposta disso?

**Comment by deboraazevedo** [comment]
Recebi no email do PyLadies uma resposta, a pessoa que respondeu copiou a Lynn no e-mail, que seria quem poderia apontar quem é a pessoa certa pra ajudar nisso, mas a Lynn não retornou o e-mail

**Comment by deboraazevedo** [comment]
Acabei esquecendo de falar aqui, mas nesse mesmo dia que respondi na thread, entrei no slack do PyLadies internacional e a Lynn falou pra eu enviar email pra ela.Enviei, mas ainda não obtive resposta

**Comment by deboraazevedo** [comment]
Gente, acabei de falar com a Lynn Root e ela me falou que alguns meses atrás ela aprovou/setou algumas locations no Brasil, semanas antes de eu enviar o email, então talvez mais requisições tenham sido feitas mais recentemente e ela disse que vai chegr nelas no fds.
