### ISSUE TITLE
[Reunião] Grupo de trabalho Comunicação: 02 maio 2021

### ISSUE THREAD

**Issue by cecivieira** [pyladies-brazil/organizacao#63]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêncide no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião Grupo de trabalho Comunicação

- Data: 02 maio 2021
- Participantes:

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) | 
 --| --| --|
 Recife| Ana Cecília Vieira| @cecivieira|
 Rio de Janeiro| Gabriela Entringe| @gaBI|
 São Carlos| Marília Calábria| --|
 Ribeirão Preto| Melissa Ribeiro| @melissarib|
 Goiânia| Gabriella Damas|--|

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Itens debatidos

- [x] Relembrar escopo do grupo de trabalho
    [Ata 21 ago. 2020](https://github.com/pyladies-brazil/organizacao/issues/19)
    
- [x] Manter *destaques* no Instagram para cada região do país e criar um story com o @ e outras redes sociais de cada comunidade local que pertence àquela região.  
    - A imagem capa do destaque deve o mapa da região.

- [x] Publicações pendentes
    - Divulgação de 2 artigos novos do blog brasil.pyladies.com
    - Boteco PyLadies maio
    - Grupo de estudo "Introdução a python: para mulheres que sabem programar em outra linguagem"
    - Divulgação do canal de notícias do Telegram nas redes sociais
    - Divulgação nas redes sociais do grupo de estudo de Bioinformática 
    
- [x] Canal de comunicação
    - Canal de notícias no Telegram
    - Instagram
    - Twitter
    - Facebook

- [x] Divisão de tarefas
     - Repost e retweet das atividades das comunidades locais nas redes sociais da PyLadies Brasil;
     - Criação de artes para divulgação em redes sociais das atividades da PyLadies Brasil;
     - 

- [x] Acesso ao Hootsuite e Canva
    - Solicitado acesso do Hotsuite para @melissarib
    - Enviado convite do grupo de trabalho no Canva para Marília e Gabriela

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|
Repost e retweet das atividades das comunidades locais nas redes sociais e canal de notícias da PyLadies Brasil | @melissarib @cecivieira | [Hootsuite](https://hootsuite.com/) e [Canal de notícias](https://t.me/pyladiesbrasil)
Arte para novo artigo no blog, ["Desvendando o DNA com Python"](https://brasil.pyladies.com/2021/04/25/desvendando-o-dna-com-python/)| @gaBI| Até 07 maio|
Arte para divulgação do Boteco maio e junho| Marília| Até 21 maio|
Arte para divulgação do canal de notícias do Telegram nas redes | Marília| Até 07 maio|
Divulgação nas redes sociais do grupo de estudo de Bioinformática |@melissarib @cecivieira|2. semana de maio
Divulgação Boteco PyLadies |@melissarib @cecivieira|Em 24 maio
Organizar destaques do Instagram| @melissarib| --|

**Comment by Emilly-horta** [comment]
posso ficar com a parte da arte tbm
