### ISSUE TITLE
Criar lojinha das Pyladies

### ISSUE THREAD

**Issue by talitarossari** [pyladies-brazil/organizacao#7]
Criar a lojinha das Pyladies em Django.
Para isso temos que definir uma estrutura de como sera os modelos, etc...
Como vocês propõem fazer isso?

**Comment by isabelapnt** [comment]
Teve uma light talk falando do [Django plus](http://djangoplus.net/), um framework que já vem com algumas configurações e template default. Uma das aplicações é de loja, a gente podia pegar a estrutura que montaram e adaptar pra nossa loja.

**Comment by jtemporal** [comment]
em tese a lojinha ta pronta né? la no repo lojinha, ate onde entendi era só fazer deploy pra uma instancia do Heroku. que também ja temos pela apyb, podemos ver isso nos sprints!

**Comment by pgrangeiro** [comment]
@isabelapnt e @jtemporal na assembléia decidimos criar uma do zero para atender as nossas necessidades. atualmete temos uma lojinha pronta usando o [Shuup](https://github.com/shuup/shuup), porém o projeto não é bem documentado e para criar uma lojinha do zero devem ser feitos muitos setups manuais.

**Comment by talitarossari** [comment]
Dito o que a @pgrangeiro falou. Teremos que reservar um tempo para fazermos a analise do que deve ter na lojinha, tanto os modelos (classes), quanto urls, e telas :)
