### ISSUE TITLE
[Reunião] Assembleia: 16/10/2021

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/organizacao#79]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêncide no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Assembleia geral

- Data: 16/10/2021 
- Participantes:

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) | 
 --| --| --|
Brasil | Jessica Temporal | @jtemporal
Parnaíba | Emily Horta | @Emilly-horta
Fortaleza | Alynne Ferreira | @alynnefs
Paraíba | Dandara Sousa | @dandaramcsousa
Manaus | Juliany Raiol | @julianyraiol
Natal | Débora Azevedo | @deboraazevedo
Recife | Juliana Barros Lima | @tiidadavena
São Paulo | Daviny Vidal | @davinyvidal
Macaé | Renata | @22renata
Fortaleza | Letícia Sampaio | @lesampaio
Brasil | Pâmella Araújo Balcaçar | @pamellabiotec
Recife | Ana Cecília | @cecivieira
São Carlos | Ana Dulce | @anadulce 
São Carlos | Juliana F. Alves | @julianafalves
Brasil | Flávia Souza Viana | @Flaviasv
Natal | Esther Aragão | @estheraragaos
Recife | Lidiane Monteiro | @lidymonteiro
Natal | Gabriela Cavalcante | @gabicavalcante
São Paulo | Isabelle Dias Ribeiro | @drisabelles
Brasil e DF | Kadidja Valéria Reginaldo de Oliveira | @kadidjah
Sergipe | Liggia Lima | @liggia
Paraíba | Elayni Franco | @elayni
São Paulo | Daviny Vidal | @davinyvidal
Sergipe | Arianne Macena | @annemacena 
Paraíba | Luciana Gomes | @lqleal
Paraíba | Iele Passos | @ielepassos

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

*** Os itens debatidos foram oriundos dos comentários dessa issue

### Itens a serem debatidos

- [x] Prestação de contas financeira
R$1.566,88 18h52 (R$660 recebidos de brindes excedentes da PYBR2019 e cerca de R$900 em dinheiro) conta Nubank Débora Azevedo. PicPay da PyLadies Brasil (R$4.953,56) Débora fez hoje, 16/10/21, a movimentação do dinheiro para  conta do picpay de @jtemporal (total de 6.520,44).
 - Publicar prestação de conta bimestralmente no repositório https://github.com/pyladies-brazil/organizacao/
 - Marcar reunião sobre estruturação financeira da PyLadies Brasil para semana de 16 de novembro de 2021 (responsável: @cecivieira)
 - Preparação da planilha de prestação de contas (reponsáveis: @jtemporal e @deboraazevedo)

- [x] PyLadies BR Conf [post-mortem da pyladies br conf I](https://deboraazevedo.github.io//post-mortem-pyladiesbrconf/)
Marcar uma reunião específica para esse tópico. O ideal é que a organização da conferência seja diferente da organização da Python Brasil.

- [x] Campanha de financimento coletivo PyLadies na Python Brasil Manaus
O email vai sair dia 21/11 chamando para a reunião para ver a disponibilidade das pessoas que se comprometeram em organizar a campanha, além de redefinir as representantes das regiões e retomar atividades. Documentação já existente: 
    https://brasil.pyladies.com/2020/02/09/a-campanha-esta-no-ar-pybr2020/

    https://brasil.pyladies.com/2020/02/13/chamada-representantes-campanha-pybr2020/

- [x] Pessoas não-binárias na comunidade
Traduzir a [issue do PyLadies Global](https://github.com/pyladies/global-organizing/issues/18)
Montar um material
Pessoas que se comprometeram: @dandaramcsousa, @gabicavalcante, @Flaviasv, @davinyvidal, @tiidadavena
Iniciar um Grupo de Trabalho de diversidade através de reunião 

- [x] retomada dos encontros presenciais
Produzir uma cartilha para eventos presenciais que foquem na necessidade de cada grupo, buscando o acolhimento das pessoas, não necessariamente com enfoque técnico (ex.: reunião em praça, parque aberto). Nessa cartilha a ser contruída coletivamente focar nas orientações locais do governo + **bom senso**, passaporte da vacina ou teste negativado. @estheraragaos, @ryllari, @kadidjah,
@lidymonteiro, @francoelayni 

Fazer pesquisa sobre como a comunidade se sente com a retomada de eventos presenciais.

Não deixar eventos online de lado, há pessoas que não se sentem confortáveis ou simplesmente não podem participar de eventos presenciais.

- [x] Conselho Global
@cecivieira e @julianafalves deixaram as atividades do Conselho Global por várias situações de silenciamento.
- [x] Papo entre pyladies, pylives, boteco das pyladies
Marcar reunião para organização dos eventos para 2022.

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|
 Fazer arte para chamar PyLadies para as reuniões | --| --|
 Mandar e-mail para marcar a reunião de reestruturação financeira | @cecivieira | --|
 Mandar e-mail para marcar a reunião sobre PyLadies Brasil Conf | @julianyraiol, @Emilly-horta| --|
 Mandar e-mail para marcar a reunião da campanha de financiamento coletivo PyLadies na PyBR2022| @jtemporal | --|
 Marcar reunião para organização dos eventos para 2022 | @pamellabiotec tec | --|

**Comment by cecivieira** [comment]
Retomada dos encontros presenciais

**Comment by cecivieira** [comment]
Introdução rede de comunidades PyLadies no Brasil

**Comment by Kadidjah** [comment]
GT Criação de materiais do Curso: Introdução a Linguagem Python
Público-alvo: mulheres que sabem programar em outras linguagem e não conhecem Python.
- [ ] Continuidade das atividades | Elaborações de questões no Hacherrank.

**Comment by cecivieira** [comment]
Público e restrições de acesso para a assembleia

**Comment by dandaramcsousa** [comment]
É papel da PyLadies ser uma comunidade também para pessoas não binárias ou continuamos com o discurso de ser apenas para mulheres?

**Comment by Ryllari** [comment]
> É papel da PyLadies ser uma comunidade também para pessoas não binárias ou continuamos com o discurso de ser apenas para mulheres?

O conselho global discutiu isso 2 anos atrás...
https://github.com/pyladies/global-organizing/issues/18

**Comment by cecivieira** [comment]
> Eu tava pensando isso hoje, acho massa um servidor no discord. Acho mais massa ainda se fosse algo global onde a gente pudesse estar mais próxima de outros capítulos regionalmente, e internacionalmente

@Ryllari existe o Slack da Global com essa proposta

**Comment by jtemporal** [comment]
Respondendo sobre a campanha: eu vou atualizar vocês dos planos, mas a ideia é só retomar a campanha com foco no próximo local que ocorrer (com fé que será Manaus)
