### ISSUE TITLE
[Reunião] PyLadies Conf Manaus: a definir

### ISSUE THREAD

**Issue by julianyraiol** [pyladies-brazil/organizacao#81]
(alguns tópicos ainda precisam ser definidos, atualizaremos logo mais)

O objetivo dessa reunião é conversar sobre a 3° edição do PyLadies Conf. O evento será realizado em Manaus e a @AliceAdativa estará como Big Kahuna com o apoio da comunidade @pyladiesmanaus também. Gostaríamos de convidar as pyladies de todo o Brasil para nos ajudarem a levantar o evento.

# Reunião PyLadies Conf

- Data: a definir
- Participantes:

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) | 
 --| --| --|

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Itens a serem debatidos

- [ ] Apresentar a proposta inicial de organizar a PyLadies Conf em Manaus
- [ ] Definir grupos de trabalho
- [ ] Definir canal oficial para a organização
- [ ] Criaremos um repositório apenas para a organização do pyladies conf?
- [ ] Ideias iniciais para a identidade visual do evento
- [ ] Definir data para a próxima reunião

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|

cc [@pyladies-conf-manaus](https://github.com/orgs/pyladies-brazil/teams/pyladies-conf-manaus/members)

**Comment by jtemporal** [comment]
oi oi tava olhando umas issues e passei por essa, temos novidades em relação a conf? ja tão organizando a chamada da reunião para falar da conf?

cx @julianyraiol

**Comment by cecivieira** [comment]
Não é obrigação da organização da PyBr organizar a PyLadies Conf. Acho que a pergunta rolou porque vocês abriram essa issue.

Em abril será realizada uma assembleia extraordinária da rede PyLadies Brasil para tratar sobre financeiro e PyLadies Conf. Caso a comunidade de Manaus siga com interesse na organização, é necessário que esteja na assembleia.

@pyladies-conf-manaus

**Comment by aliceadativa** [comment]
@cecivieira @jtemporal sou do PyLadies Manaus e estarei na organização do PyLadies Conf.

Antes da assembleia extraordinária acredito que seria bom termos uma reunião inicial sobre o evento, por isso criei um [Doodle ](https://doodle.com/meeting/participate/id/nelWPNgd) para divulgar no grupo e agendar a reunião para a semana que vem, tudo bem?

**Comment by jtemporal** [comment]
@aliceadativa acho importantíssimo enviar esse doodle no e-mail do pyladies e colocar lá no slack, eu não recebi as notificações daqui e acredito que é o mesmo caso de mais pessoas que tenham interesse. Pode mandar lá por gentileza? Desde já agradeço.

**Comment by cecivieira** [comment]
Oi povo,

Como informei [há uns comentários antes](https://github.com/pyladies-brazil/organizacao/issues/81#issuecomment-1069041324), faremos uma assembleia extraordinária agora em abril para conversar sobre financeiro e PyLadies Conf.

Enviei o Doodle para a lista de e-mail e Slack. Caso a comunidade de Manaus siga com interesse na organização, é necessário que esteja na assembleia.

Vou fechar essa issue, pois essa reunião de intenção se transformou em uma pauta da assembleia.
Beijo
