### ISSUE TITLE
[Reunião] Reestruturação financeira: 16 nov. 2021

### ISSUE THREAD

**Issue by cecivieira** [pyladies-brazil/organizacao#82]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêncide no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Reunião de Reestruturação Financeira

- Data: 19 nov. 2021
- Participantes:

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) | 
 -|-|-|
 Fortaleza| Alynne Ferreira| @alynnefs|
 Brasil/DF| Kadidja Valéria| @Kadidjah |
 Recife | Ana Cecília | @cecivieira |
 Recife | Lidiane Monteiro | @lidymonteiro|
 Curitiba| Ana Paula Carneiro | @anacsv|
 Natal| Débora Azevedo | @deboraazevedo|
 São Carlos | Ana Dulce | @anadulce|
 
 

### Itens a serem debatidos

- [x] O fluxo de Caixa da PyLadies Brasil, atual no valor de R$6.520,44, proposta aprovada: usar a APyB, como pessoa jurídica, para guardar o dinheiro, suporte financeira contábil e jurídico.
    - **Pontos positivos:** usar estrutura já estabelecida (não precisar reinventar a roda), ter uma entidade jurídica para recebimento de patrocínio, segurança financeira.
    - **Pontos negativos:** necessitar de comprovação (nota fiscal, boleto, fatura do cartão ou recibo) para reembolso, caso pagamento não seja realizado diretamente pela associação.
- [x] Para a associar-se as informações estão disponíveis em https://associacao.python.org.br/
- [x] Estabelecer frequência e metodologia para prestação pública de contas
    Realizar alinhamento com nova gestão da APyB (a partir de 15 jan.) sobre como é realizada a atual prestação de conta da associação e como será a sinalização dos gastos e saldo referentes a PyLadies Brasil + Criar espaço no site da PyLadies Brasil e linkar com a prestação de conta da associação
- [x] Forma de receber apoio financeiro
    Escrever texto padrão e inserir no [Repositório da Organização](https://github.com/pyladies-brazil/organizacao) sobre como receber apoio financeiro
- [x] Estabelecer critérios para uso do dinheiro
    Iniciar documento e fazer chamada na lista de e-mails para desenvolver critérios para uso do dinheiro.

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|
 Enviar e-mail para ApyB manifestando interesse em usá-la como pessoa jurídica para  guardar o dinheiro, suporte financeira contábil e jurídico e solicitando orientações sobre como proceder a transferência do caixa atual da conta de  @jtemporal para a associação (copiar lista de e-mail da PyLadies Brasil)| @cecivieira| --|
Alinhar com nova gestão da APyB (a partir de 15 jan.) sobre como é realizada a atual prestação de conta da associação e como será a sinalização dos gastos e saldo referentes a PyLadies Brasil| --| --|
Criar espaço no site da PyLadies Brasil e linkar com a prestação de conta da associação| @pyladies-brazil/tech| --|
Escrever texto padrão e inserir no [Repositório da Organização](https://github.com/pyladies-brazil/organizacao) sobre como receber apoio financeiro| --| --|
Iniciar documento e fazer chamada na lista de e-mails para desenvolver critérios para uso do dinheiro| @cecivieira @anadulce @alynnefs| [Rascunho](https://docs.google.com/document/d/1bDmafAFTIFKpK-1MGTSbUXYAlvMs5FGkU8Csd8cQbF8/edit?usp=sharing)|

cc @<GitHub team do grupo de trabalho responsável pela reunião>

**Comment by Kadidjah** [comment]
Por favor, gostaria de acrescentar esse tópico: 

- como se associar ApyB e de que forma se faz o pagamento da anuidade.
