### ISSUE TITLE
[Reunião] Organização da campanha de apoio financeiro: 20/12/2021

### ISSUE THREAD

**Issue by jtemporal** [pyladies-brazil/organizacao#83]
# Reunião: Organização da campanha de apoio financeiro

- Data: 20/12/2021
- Participantes:

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) | 
 --| --| --|
 PyLadies Recife | Ana Cecília Vieira | @cecivieira
 PyLadies Brasil | Jessica Temporal | @jtemporal
 PyLadies DF | Kadidja Oliveira | @kadidjah
 PyLadies Natal | Débora Azevedo | @deboraazevedo
 PyLadies São Paulo | Vanessa Nunes | @vanessanunes
 PyLadies Curitiba | Ana Paula Carneiro | @anacsv
 PyLadies São Carlos | Ana Dulce Padovan | @anadulce

## Ata

1. Relembrar o novo formato
1. O que foi feito
1. Oficializar a situação do time atual
1. Escolha da data para chamada de novo time (seja para continuar a campanha como está ou para iniciar uma campanha nova)

### Itens a serem debatidos

- [x] Breve histórico da Campanha PyLadies na Python Brasil
    Era levantada a quantidade de mulheres que necessitava de apoio financeiro, com isso íamos em busca do dinheiro. Após algum tempo, passamos a coletar o dinheiro e depois fazer a seleção de mulheres que seriam beneficiadas. No ano seguinte, passamos a ter representantes estaduais para facilitar a divulgação e gestão da campanha.
    Nos anos de 2020 e 2021 a campanha foi paralisada devido a pandemia e ausência de eventos presenciais.
- [x] Oficializar a situação do time atual
    Tem 05 (cinco) pessoas no grupo de organização da Campanha, sendo necessária revisão de toda a campanha, tendo em vista que o planejamento atual foi realizado há 02 (dois) anos atrás.
    As representantes regionais tem como objetivo participar das decisões da campanha, divulgar campanha na(s) sua(s) comunidade(s) regional(is), dar apoio a mulheres da sua comunidade interessadas em solicitar apoio financeiro e contato com patrocinadoras em potencial da sua região.
    Critérios para ser representante:
    * Disposição e interesse;
    * Participar de uma comunidade da região/estado de representação;
    * Ter/buscar ter uma boa comunicação com a comunidade local;
- [x] Escolha de nova capitania
    Ana Cecília Vieira @cecivieira, Jessica Temporal vai se afastar da capitania, e ficará responsável de ajudar a transição enquanto houver necessidade
- [x] Escolha da data para primeira ruenião oficial
    Será feito um doodle para escolha oficial da data que deverá ocorrer na semana do dia 10 de janeiro

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|
 Marcar reunião de transição de gestão | @cecivieira | -- |
 Criar doodle para escolha da data na semana do dia 10 de janeiro | @cecivieira | -- |
 Marcar primeira reunião de campanha | @cecivieira | -- |

**Comment by Kadidjah** [comment]
(Sugestão para ponto de pauta.)
5. Minuta de um modelo híbrido para a Python Brasil 2022 em Manaus.

**Comment by cecivieira** [comment]
@Kadidjah tu poderia detalhar um pouquinho mais o que seria o modelo híbrido?
Não entendi bem. Seria o modelo híbrido de financiamento coletivo?

PS: A tua nova foto de perfil tá linda!!!

**Comment by Kadidjah** [comment]
Obrigada @cecivieira! 
Sim, um _modelo híbrido para o financiamento coletivo_ que vise a busca de investidores para a realização do evento em si. Algo como o crowfunding: []([](https://www.sympla.com.br/blog/5-passos-realizar-crowdfunding-para-eventos/)). 
A ideia é mapear esses investidores e pedir o apoio para as passagens, por exemplo. 
Será que já discutiram sobre esse modelo? 
Vamos conversando :)

**Comment by jtemporal** [comment]
@Kadidjah sim, esse modelo já é o que estava em ação antes do cancelamento dos eventos presenciais. Como já fazem mais de dois anos da decisão do novo formato vamos retomar como funciona esse novo formato na reuniao para que todas estejam cientes.

da uma olhada [neste post](https://brasil.pyladies.com/2020/02/13/chamada-representantes-campanha-pybr2020/) e [nesse outro post](https://brasil.pyladies.com/2020/02/09/a-campanha-esta-no-ar-pybr2020/) pra ficar por dentro :)
