### ISSUE TITLE
[Reunião] Assembleia: 21 out. 2022

### ISSUE THREAD

**Issue by cecivieira** [pyladies-brazil/organizacao#87]
_Este template deve ser editado com os itens a serem discutidos durante a reunião. Toda colaboração é bem vinda. Durante a reunião devem ser registradas as participantes e as decisões tomadas, caso hajam informações sensíveis, deve ser criado um apêncide no Google Drive do brasil@pyladies.com e o link inserido nessa issue. Após o encerramento, o grupo responsável pela reunião deve revisar as informações e fechar a issue em não mais do que uma semana._

# Assembleia geral

- Data: 21 nov. 2022
- Participantes:

Capítulo| Nome e sobrenome | @GitHub ou e-mail (opcional) | 
 --| --| --|
PyLadies Recife | Ana Cecília Vieira | @cecivieira|
PyLadies Brasil | Jessica Temporal | @jtemporal|
PyLadies Brasil - Bioinfo | Pâmella Araújo Balcaçar | @pamellabiotec |
PyLadies Recife | Lidiane Monteiro | @lidymonteiro |
--| Allana Cardoso |@ |
PyLadies Paraíba| Dandara Sousa |@ |
PyLadies São Carlos | Juliana Alves | @julianafalves|
PyLadies São Carlos | Ana Dulce | @anadulce |
--| Ana Carla| --|
PyLadies São Carlos| Juliana Sousa| --|
PyLadies São Carlos| Thayana Tavares| --|
PyLadies São Carlos| Natália Coutouné| --|
PyLadies Fortaleza| Allyne Ferreira| --|
PyLadies Recife| Juliana Albuquerque| --|
PyLadies Natal | Isadora Morena| --|
PyLadies Recife| Mariana Bedran| --|
PyLadies Recife| Olga| --|
PyLadies Manaus| Giovana de Lucca| --|
PyLadies Rio de Janeiro| Thais Vianna| --|
PyLadies Natal| Andressa Lima| --|
PyLadies Recife| Anicely Santos| --|
PyLadies Recife| Elis Grace| --|
PyLadies Salvador| Lorena Pereira| --|
PyLadies DF| Sarah Tuyani| --|

## Ata

_Adicione os itens a serem discutidos durante a reunião. Certifique-se de que você estará presente na reunião, pois a ata só pode ser editada por quem a criou_

### Acompanhamento das ações pendentes da última reunião

Atividade| Responsável | Link útil| Observações|
 --| --| --| --|

### Itens a serem debatidos

- [x]Apresentação e votação parágrafo a parágrafo do documento de "Gestão Financeira da rede PyLadies Brasil"

Trecho aprovado:

Gestão Financeira da Rede PyLadies Brasil

Este documento tem como objetivo estabelecer critérios e fluxo de autorização para utilização de recursos financeiros da Rede de comunidades PyLadies Brasil, a qual tem como foco instigar mulheres (cis e trans) e pessoas não-binárias a serem participantes ativas e líderes da comunidade de código aberto de Python.

1. Definições
Rede de comunidades PyLadies Brasil: a rede de comunidades PyLadies Brasil é composta por todos os capítulos oficiais PyLadies em território brasileiro.
APyB: Associação Python Brasil
GT: Grupo de Trabalho

2. Das Origens de Recursos Financeiros
Os recursos financeiros da rede de comunidades PyLadies Brasil são oriundos de parcerias, patrocínios, doações, vendas de produtos e/ou serviços.
Parágrafo único: não pode ser arrecadado financiamento para outro propósito que não siga os critérios de utilização descritos abaixo.

3. Critérios para utilização
É permitido o uso de recurso financeiro para a aquisição de produtos e serviços nas seguintes categorias:
Organização de eventos gratuitos;
Auxílio financeiro para viabilizar participação de PyLadies em eventos presenciais;
Melhora da acessibilidade de atividades;
Pagamento de infraestrutura para funcionamento da Rede (por exemplo: plataforma de gerenciamento de redes sociais, credenciais e senhas);
Confecção, desenvolvimento e/ou organização de produtos para comercialização.
Parágrafo único: caso um gasto não caiba nas categorias acima, a sua aprovação deve ser feita através de uma reunião da comunidade, seguindo o fluxo normal da Rede para discussão e deliberação.

4. Fluxo de aprovação de uso dos recursos financeiros
Deve seguir o passo a passo abaixo, de acordo com a sua atribuição:

Comunidade - Criação de issue para pagamento no repositório de organização no GitHub;
Grupo de Trabalho Financeiro (GT Financeiro) - Garantir o preenchimento correto da issue*;
GT Financeiro - Interagir com a APyB para pagamento;
GT Financeiro - Fechar a issue de referência na finalização do pagamento.**
* É vetado o pedido de pagamento para a APyB sem a respectiva issue no GitHub.
** O GT Financeiro deve publicar uma justificativa para todo caso de reprovação do pedido requisitado na issue.
Parágrafo único: O GT Financeiro se compromete a fornecer a primeira resposta às issues abertas em um prazo de até 3 dias e trazer as informações da APyB em até 15 dias corridos  abertura da issue.

5. Grupo de Trabalho Financeiro
O Grupo de Trabalho Financeiro (GT Financeiro) é responsável por estabelecer e manter os processos de fluxo financeiro da Rede, bem como a sua documentação. Pode ser composto por todas as pessoas interessadas em participar.

5.1 Das representantes
As representantes do GT Financeiro terão como função representar a Rede junto à APyB para assuntos regulados por este documento. 

Cabe as representantes enquanto durar o mandato:
Garantir o funcionamento do GT com transparência e fiabilidade;
Garantir o acompanhamento do balanço financeiro do caixa junto a APyB e;
Promover a transparência sobre o uso dos recursos financeiros de acordo com as regras de anonimização de dados da APyB;
Difundir e publicar amplamente o fluxo financeiro da Rede.

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|
Convocar Assembleia extraordinária a fim de concluir a aprovação do documento de "Gestão Financeira da rede PyLadies Brasil", prazo: 15 dias| @cecivieira| --|

--------------
Fotos: https://photos.app.goo.gl/EgkFzx3fjdPTdyJfA

**Comment by cecivieira** [comment]
- Apresentação e aprovação da sistemática para gestão financeira

**Comment by julianafalves** [comment]
- Construção de uma base de dados para melhor organizar as informações da redes 
     Discutir: 
   - Quais dados são importantes guardar? Porque?
   - Importância de saber a diversidade dos capitulos
   - Anonimidade opcional ou padrão
   - Pylady organizadora e Pylady participante

**Comment by cecivieira** [comment]
Eleição para representantes da Rede junto a APyB

**Comment by cecivieira** [comment]
Organização Python Brasil 2023.

**Comment by cecivieira** [comment]
Rascunho: https://hackmd.io/@IAA8H7ZURCejO-4Zz31Dug/BJnOpugVs

**Comment by cecivieira** [comment]
Convocada a assembleia extraordinária (#92) para conclusão do documento "Gestão Financeira da Rede PyLadies Brasil", coforme determinado na assembleia geral.
