### ISSUE TITLE
Criar postagem de agradecimento para doadores da campanha PyBR[13]

### ISSUE THREAD

**Issue by pgrangeiro** [pyladies-brazil/organizacao#9]
É preciso criar uma postagem em nosso site de agradecimento para todos os doadores da nossa campanha para a PyBR[13]. A postagem deve ser feita até o dia 13/10.

**Comment by anapauladsmendes** [comment]
Como seria o formato da postagem? Posso tentar ajudar!

**Comment by letuche** [comment]
Onde eu encontro a lista completa de contribuintes?

**Comment by pgrangeiro** [comment]
No nosso drive em Eventos > PyBR13
Quem quiser acesso, me manda o email em pvt no Telegram

**Comment by letuche** [comment]
Só confirmando, é esse arquivo aqui, certo?
https://docs.google.com/spreadsheets/d/1gxkQ4EmFNFHGLca2_AJloj7bk59z5MzOrzGGLImgi08/edit#gid=1546157552
E quem está marcado como "sim" na segunda coluna "Anônimo" (tem 2) não é pra entrar no post. OK?

**Comment by pgrangeiro** [comment]
Exatamente o/

**Comment by deboraazevedo** [comment]
Conseguimos fazer esse post? (pra poder marcar a issue resolvida)
